[versions]
# Plugins
kotlin = "2.4.10"
dokka = "2.2.0"
shadow = "9.6.1"
hangar = "0.1.4"
minotaur = "2.9.0"

# Libraries
bukkit = "1.8.8-R0.1-SNAPSHOT"
netty = "4.1.97.Final"
papi = "2.11.6"
luckperms = "5.4"
adventure = "4.25.0"
worldguardV6 = "6.2"
worldguardV7 = "7.0.0"
bStats = "3.2.1"
semver = "2.1.0"
objenesis = "3.5"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
# Bukkit
bukkit = { module = "org.bukkit:bukkit", version.ref = "bukkit" }
netty = { module = "io.netty:netty-transport", version.ref = "netty" }
papi = { module = "me.clip:placeholderapi", version.ref = "papi" }
luckperms = { module = "net.luckperms:api", version.ref = "luckperms" }

# Adventure
adventureMiniMessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventureSerializer = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }

# WorldGuard
worldguardV6 = { module = "com.sk89q.worldguard:worldguard-legacy", version.ref = "worldguardV6" }
worldguardV7 = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguardV7" }

# bStats
bStatsBukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bStats" }

# Utilities
semver = { module = "net.swiftzer.semver:semver", version.ref = "semver" }
objenesis = { module = "org.objenesis:objenesis", version.ref = "objenesis" }
